Map map = {
'Quantidade': 58,
'id' '417EFE3': {
'Tipo': 'Controle',
'Serial': '417EFE3',
'Controlador/ID': '0A98',
'Unidade': '0',
'Grupo': '170',
'Rec Destino': '1 ',
'Identificacao': 'ALEXANDRE TECNICO',
'Ultimo Acionamento': '4',
'Status de bateria': '0',
'Veiculo/Marca': 'PEUGEOT | PRATA | AAA1234',
},
'id' '4F2EE4': {
'Tipo': 'Cartão',
'Serial': '4F2EE4',
'Controlador/ID': '- - - -',
'Unidade': '0',
'Grupo': '0',
'Rec Destino': '1 ',
'Identificacao': 'PAULO',
'Ultimo Acionamento': '0',
'Status de bateria': '- - - -',
'Veiculo/Marca': 'SEM VEICULO',
},
'id' '12765C1': {
'Tipo': 'Controle',
'Serial': '12765C1',
'Controlador/ID': '0006',
'Unidade': '0',
'Grupo': '0',
'Rec Destino': '',
'Identificacao': '00003',
'Ultimo Acionamento': '0',
'Status de bateria': '0',
'Veiculo/Marca': 'BMW | AMARELO | AAA1111',
},
'id' '41C18DC': {
'Tipo': 'Controle',
'Serial': '41C18DC',
'Controlador/ID': '09BF',
'Unidade': '0',
'Grupo': '0',
'Rec Destino': '1 2 ',
'Identificacao': 'ZELADOR',
'Ultimo Acionamento': '0',
'Status de bateria': '0',
'Veiculo/Marca': 'AUDI | AZUL | AAA1111',
},
'id' '41C18D9': {
'Tipo': 'Controle',
'Serial': '41C18D9',
'Controlador/ID': '08D0',
'Unidade': '0',
'Grupo': '0',
'Rec Destino': '1 2 ',
'Identificacao': 'ZELADOR',
'Ultimo Acionamento': '1',
'Status de bateria': '0',
'Veiculo/Marca': 'AUDI | AMARELO | AAA1111',
},
'id' '127650C': {
'Tipo': 'Controle',
'Serial': '127650C',
'Controlador/ID': '0ABC',
'Unidade': '91',
'Grupo': '0',
'Rec Destino': '1 2 ',
'Identificacao': 'SANDERO',
'Ultimo Acionamento': '1',
'Status de bateria': '0',
'Veiculo/Marca': 'RENAULT | CINZA | OPZ7023',
},
'id' '127639C': {
'Tipo': 'Controle',
'Serial': '127639C',
'Controlador/ID': '0042',
'Unidade': '94',
'Grupo': '0',
'Rec Destino': '1 2 ',
'Identificacao': '00007',
'Ultimo Acionamento': '1',
'Status de bateria': '7',
'Veiculo/Marca': 'AUDI | AMARELO | AAA1111',
},
'id' '12761C5': {
'Tipo': 'Controle',
'Serial': '12761C5',
'Controlador/ID': '03AC',
'Unidade': '22',
'Grupo': '0',
'Rec Destino': '1 2 ',
'Identificacao': '00008',
'Ultimo Acionamento': '2',
'Status de bateria': '0',
'Veiculo/Marca': 'AUDI | AMARELO | AAA1111',
},
'id' '1276348': {
'Tipo': 'Controle',
'Serial': '1276348',
'Controlador/ID': '1246',
'Unidade': '0',
'Grupo': '0',
'Rec Destino': '1 ',
'Identificacao': '00009',
'Ultimo Acionamento': '1',
'Status de bateria': '15',
'Veiculo/Marca': 'AUDI | AMARELO | AAA1111',
},
'id' '41C4CB4': {
'Tipo': 'Controle',
'Serial': '41C4CB4',
'Controlador/ID': '00FE',
'Unidade': '0',
'Grupo': '0',
'Rec Destino': '1 ',
'Identificacao': '00010',
'Ultimo Acionamento': '1',
'Status de bateria': '0',
'Veiculo/Marca': 'SEM VEICULO',
},
'id' '41C368B': {
'Tipo': 'Controle',
'Serial': '41C368B',
'Controlador/ID': '0989',
'Unidade': '0',
'Grupo': '0',
'Rec Destino': '1 ',
'Identificacao': '00011',
'Ultimo Acionamento': '1',
'Status de bateria': '0',
'Veiculo/Marca': 'SEM VEICULO',
},
'id' '41C3636': {
'Tipo': 'Controle',
'Serial': '41C3636',
'Controlador/ID': '1461',
'Unidade': '0',
'Grupo': '0',
'Rec Destino': '1 ',
'Identificacao': '00012',
'Ultimo Acionamento': '1',
'Status de bateria': '0',
'Veiculo/Marca': 'SEM VEICULO',
},
'id' '41C3626': {
'Tipo': 'Controle',
'Serial': '41C3626',
'Controlador/ID': '0F56',
'Unidade': '0',
'Grupo': '0',
'Rec Destino': '1 ',
'Identificacao': '00013',
'Ultimo Acionamento': '1',
'Status de bateria': '0',
'Veiculo/Marca': 'SEM VEICULO',
},
'id' '41C367D': {
'Tipo': 'Controle',
'Serial': '41C367D',
'Controlador/ID': '054F',
'Unidade': '0',
'Grupo': '0',
'Rec Destino': '1 ',
'Identificacao': '00014',
'Ultimo Acionamento': '1',
'Status de bateria': '0',
'Veiculo/Marca': 'SEM VEICULO',
},
'id' '41C3692': {
'Tipo': 'Controle',
'Serial': '41C3692',
'Controlador/ID': '0A74',
'Unidade': '0',
'Grupo': '0',
'Rec Destino': '1 ',
'Identificacao': '00015',
'Ultimo Acionamento': '1',
'Status de bateria': '0',
'Veiculo/Marca': 'SEM VEICULO',
},
'id' '41C1758': {
'Tipo': 'Controle',
'Serial': '41C1758',
'Controlador/ID': '090B',
'Unidade': '0',
'Grupo': '0',
'Rec Destino': '1 ',
'Identificacao': '00016',
'Ultimo Acionamento': '1',
'Status de bateria': '0',
'Veiculo/Marca': 'EDITAVEL | AZUL | AAA1111',
},
'id' '41C3829': {
'Tipo': 'Controle',
'Serial': '41C3829',
'Controlador/ID': '19E9',
'Unidade': '0',
'Grupo': '0',
'Rec Destino': '1 ',
'Identificacao': '00017',
'Ultimo Acionamento': '1',
'Status de bateria': '0',
'Veiculo/Marca': 'EDITAVEL | AZUL | AAA1111',
},
'id' '41C3697': {
'Tipo': 'Controle',
'Serial': '41C3697',
'Controlador/ID': '1076',
'Unidade': '0',
'Grupo': '0',
'Rec Destino': '1 ',
'Identificacao': '00018',
'Ultimo Acionamento': '1',
'Status de bateria': '0',
'Veiculo/Marca': 'EDITAVEL | AZUL | AAA1111',
},
'id' '41C3634': {
'Tipo': 'Controle',
'Serial': '41C3634',
'Controlador/ID': '0028',
'Unidade': '0',
'Grupo': '0',
'Rec Destino': '1 ',
'Identificacao': '00019',
'Ultimo Acionamento': '1',
'Status de bateria': '0',
'Veiculo/Marca': 'EDITAVEL | AZUL | AAA1111',
},
'id' '41C18D8': {
'Tipo': 'Controle',
'Serial': '41C18D8',
'Controlador/ID': '18B4',
'Unidade': '0',
'Grupo': '0',
'Rec Destino': '1 ',
'Identificacao': '00020',
'Ultimo Acionamento': '2',
'Status de bateria': '0',
'Veiculo/Marca': 'EDITAVEL | AZUL | AAA1111',
},
'id' '41C361C': {
'Tipo': 'Controle',
'Serial': '41C361C',
'Controlador/ID': '07B2',
'Unidade': '1000',
'Grupo': '0',
'Rec Destino': '1 ',
'Identificacao': '00021',
'Ultimo Acionamento': '1',
'Status de bateria': '0',
'Veiculo/Marca': 'AUDI | AMARELO |        ',
},
'id' '41C196A': {
'Tipo': 'Controle',
'Serial': '41C196A',
'Controlador/ID': '0793',
'Unidade': '0',
'Grupo': '0',
'Rec Destino': '1 ',
'Identificacao': '00022',
'Ultimo Acionamento': '1',
'Status de bateria': '0',
'Veiculo/Marca': 'SEM VEICULO',
},
'id' '41C364F': {
'Tipo': 'Controle',
'Serial': '41C364F',
'Controlador/ID': '006B',
'Unidade': '0',
'Grupo': '0',
'Rec Destino': '1 ',
'Identificacao': '00023',
'Ultimo Acionamento': '1',
'Status de bateria': '0',
'Veiculo/Marca': 'SEM VEICULO',
},
'id' '41C3681': {
'Tipo': 'Controle',
'Serial': '41C3681',
'Controlador/ID': '106E',
'Unidade': '0',
'Grupo': '0',
'Rec Destino': '1 ',
'Identificacao': '00024',
'Ultimo Acionamento': '1',
'Status de bateria': '0',
'Veiculo/Marca': 'SEM VEICULO',
},
'id' '41C195F': {
'Tipo': 'Controle',
'Serial': '41C195F',
'Controlador/ID': '0028',
'Unidade': '0',
'Grupo': '0',
'Rec Destino': '1 ',
'Identificacao': '00025',
'Ultimo Acionamento': '2',
'Status de bateria': '0',
'Veiculo/Marca': 'SEM VEICULO',
},
'id' '41C4EE6': {
'Tipo': 'Controle',
'Serial': '41C4EE6',
'Controlador/ID': '14DC',
'Unidade': '0',
'Grupo': '0',
'Rec Destino': '1 ',
'Identificacao': '00026',
'Ultimo Acionamento': '1',
'Status de bateria': '0',
'Veiculo/Marca': 'SEM VEICULO',
},
'id' '41C18DF': {
'Tipo': 'Controle',
'Serial': '41C18DF',
'Controlador/ID': '091C',
'Unidade': '0',
'Grupo': '0',
'Rec Destino': '1 ',
'Identificacao': '00027',
'Ultimo Acionamento': '1',
'Status de bateria': '0',
'Veiculo/Marca': 'SEM VEICULO',
},
'id' '41C18DA': {
'Tipo': 'Controle',
'Serial': '41C18DA',
'Controlador/ID': '0E70',
'Unidade': '0',
'Grupo': '0',
'Rec Destino': '1 ',
'Identificacao': '00028',
'Ultimo Acionamento': '1',
'Status de bateria': '0',
'Veiculo/Marca': 'SEM VEICULO',
},
'id' '41C3622': {
'Tipo': 'Controle',
'Serial': '41C3622',
'Controlador/ID': '0064',
'Unidade': '0',
'Grupo': '0',
'Rec Destino': '1 ',
'Identificacao': '00029',
'Ultimo Acionamento': '2',
'Status de bateria': '0',
'Veiculo/Marca': 'SEM VEICULO',
},
'id' '41C3630': {
'Tipo': 'Controle',
'Serial': '41C3630',
'Controlador/ID': '1DAE',
'Unidade': '0',
'Grupo': '0',
'Rec Destino': '1 ',
'Identificacao': '00030',
'Ultimo Acionamento': '1',
'Status de bateria': '0',
'Veiculo/Marca': 'SEM VEICULO',
},
'id' '41C176E': {
'Tipo': 'Controle',
'Serial': '41C176E',
'Controlador/ID': '053D',
'Unidade': '0',
'Grupo': '0',
'Rec Destino': '1 ',
'Identificacao': '00031',
'Ultimo Acionamento': '1',
'Status de bateria': '0',
'Veiculo/Marca': 'SEM VEICULO',
},
'id' '41C368A': {
'Tipo': 'Controle',
'Serial': '41C368A',
'Controlador/ID': '0085',
'Unidade': '0',
'Grupo': '0',
'Rec Destino': '1 ',
'Identificacao': '00032',
'Ultimo Acionamento': '1',
'Status de bateria': '0',
'Veiculo/Marca': 'SEM VEICULO',
},
'id' '41C3654': {
'Tipo': 'Controle',
'Serial': '41C3654',
'Controlador/ID': '07C3',
'Unidade': '0',
'Grupo': '0',
'Rec Destino': '1 ',
'Identificacao': '00033',
'Ultimo Acionamento': '2',
'Status de bateria': '0',
'Veiculo/Marca': 'SEM VEICULO',
},
'id' '41C18E4': {
'Tipo': 'Controle',
'Serial': '41C18E4',
'Controlador/ID': '0015',
'Unidade': '0',
'Grupo': '0',
'Rec Destino': '1 ',
'Identificacao': '00034',
'Ultimo Acionamento': '2',
'Status de bateria': '0',
'Veiculo/Marca': 'SEM VEICULO',
},
'id' '41C382D': {
'Tipo': 'Controle',
'Serial': '41C382D',
'Controlador/ID': '0277',
'Unidade': '0',
'Grupo': '0',
'Rec Destino': '1 ',
'Identificacao': '00035',
'Ultimo Acionamento': '2',
'Status de bateria': '0',
'Veiculo/Marca': 'SEM VEICULO',
},
'id' '41C18EA': {
'Tipo': 'Controle',
'Serial': '41C18EA',
'Controlador/ID': '0EF2',
'Unidade': '0',
'Grupo': '0',
'Rec Destino': '1 ',
'Identificacao': '00036',
'Ultimo Acionamento': '1',
'Status de bateria': '0',
'Veiculo/Marca': 'SEM VEICULO',
},
'id' '41C3689': {
'Tipo': 'Controle',
'Serial': '41C3689',
'Controlador/ID': '08D0',
'Unidade': '0',
'Grupo': '0',
'Rec Destino': '1 ',
'Identificacao': '00037',
'Ultimo Acionamento': '1',
'Status de bateria': '2',
'Veiculo/Marca': 'SEM VEICULO',
},
'id' '41C20BA': {
'Tipo': 'Controle',
'Serial': '41C20BA',
'Controlador/ID': '0AE8',
'Unidade': '0',
'Grupo': '0',
'Rec Destino': '1 ',
'Identificacao': '00038',
'Ultimo Acionamento': '2',
'Status de bateria': '0',
'Veiculo/Marca': 'SEM VEICULO',
},
'id' '41C18F4': {
'Tipo': 'Controle',
'Serial': '41C18F4',
'Controlador/ID': '0B5F',
'Unidade': '0',
'Grupo': '0',
'Rec Destino': '1 ',
'Identificacao': '00039',
'Ultimo Acionamento': '1',
'Status de bateria': '0',
'Veiculo/Marca': 'SEM VEICULO',
},
'id' '41C3816': {
'Tipo': 'Controle',
'Serial': '41C3816',
'Controlador/ID': '028B',
'Unidade': '0',
'Grupo': '0',
'Rec Destino': '1 ',
'Identificacao': '00040',
'Ultimo Acionamento': '1',
'Status de bateria': '0',
'Veiculo/Marca': 'SEM VEICULO',
},
'id' '41C18E6': {
'Tipo': 'Controle',
'Serial': '41C18E6',
'Controlador/ID': '01D3',
'Unidade': '0',
'Grupo': '0',
'Rec Destino': '1 ',
'Identificacao': '00041',
'Ultimo Acionamento': '1',
'Status de bateria': '0',
'Veiculo/Marca': 'SEM VEICULO',
},
'id' '41C3820': {
'Tipo': 'Controle',
'Serial': '41C3820',
'Controlador/ID': '01C2',
'Unidade': '0',
'Grupo': '0',
'Rec Destino': '1 ',
'Identificacao': '00042',
'Ultimo Acionamento': '1',
'Status de bateria': '0',
'Veiculo/Marca': 'SEM VEICULO',
},
'id' '41C196C': {
'Tipo': 'Controle',
'Serial': '41C196C',
'Controlador/ID': '0032',
'Unidade': '0',
'Grupo': '0',
'Rec Destino': '1 ',
'Identificacao': '00043',
'Ultimo Acionamento': '1',
'Status de bateria': '0',
'Veiculo/Marca': 'SEM VEICULO',
},
'id' '41C367B': {
'Tipo': 'Controle',
'Serial': '41C367B',
'Controlador/ID': '0008',
'Unidade': '0',
'Grupo': '0',
'Rec Destino': '1 ',
'Identificacao': '00044',
'Ultimo Acionamento': '0',
'Status de bateria': '0',
'Veiculo/Marca': 'SEM VEICULO',
},
'id' '41C362C': {
'Tipo': 'Controle',
'Serial': '41C362C',
'Controlador/ID': '0009',
'Unidade': '0',
'Grupo': '0',
'Rec Destino': '1 ',
'Identificacao': '00045',
'Ultimo Acionamento': '0',
'Status de bateria': '0',
'Veiculo/Marca': 'SEM VEICULO',
},
'id' '41C1935': {
'Tipo': 'Controle',
'Serial': '41C1935',
'Controlador/ID': '04FB',
'Unidade': '0',
'Grupo': '0',
'Rec Destino': '1 ',
'Identificacao': '00046',
'Ultimo Acionamento': '1',
'Status de bateria': '12',
'Veiculo/Marca': 'SEM VEICULO',
},
'id' '41C2099': {
'Tipo': 'Controle',
'Serial': '41C2099',
'Controlador/ID': '000A',
'Unidade': '0',
'Grupo': '0',
'Rec Destino': '1 ',
'Identificacao': '00047',
'Ultimo Acionamento': '3',
'Status de bateria': '0',
'Veiculo/Marca': 'SEM VEICULO',
},
'id' '41C175E': {
'Tipo': 'Controle',
'Serial': '41C175E',
'Controlador/ID': '0008',
'Unidade': '0',
'Grupo': '0',
'Rec Destino': '1 ',
'Identificacao': '00048',
'Ultimo Acionamento': '0',
'Status de bateria': '0',
'Veiculo/Marca': 'SEM VEICULO',
},
'id' '41C368E': {
'Tipo': 'Controle',
'Serial': '41C368E',
'Controlador/ID': '0007',
'Unidade': '0',
'Grupo': '0',
'Rec Destino': '1 ',
'Identificacao': '00049',
'Ultimo Acionamento': '0',
'Status de bateria': '0',
'Veiculo/Marca': 'SEM VEICULO',
},
'id' '41C4A60': {
'Tipo': 'Controle',
'Serial': '41C4A60',
'Controlador/ID': '000B',
'Unidade': '0',
'Grupo': '0',
'Rec Destino': '1 ',
'Identificacao': '00050',
'Ultimo Acionamento': '0',
'Status de bateria': '0',
'Veiculo/Marca': 'SEM VEICULO',
},
'id' '41C3693': {
'Tipo': 'Controle',
'Serial': '41C3693',
'Controlador/ID': '000B',
'Unidade': '0',
'Grupo': '0',
'Rec Destino': '1 ',
'Identificacao': '00051',
'Ultimo Acionamento': '0',
'Status de bateria': '0',
'Veiculo/Marca': 'SEM VEICULO',
},
'id' '41C368F': {
'Tipo': 'Controle',
'Serial': '41C368F',
'Controlador/ID': '0006',
'Unidade': '0',
'Grupo': '0',
'Rec Destino': '1 ',
'Identificacao': '00052',
'Ultimo Acionamento': '0',
'Status de bateria': '0',
'Veiculo/Marca': 'SEM VEICULO',
},
'id' '41C175C': {
'Tipo': 'Controle',
'Serial': '41C175C',
'Controlador/ID': '0314',
'Unidade': '0',
'Grupo': '0',
'Rec Destino': '1 ',
'Identificacao': '00053',
'Ultimo Acionamento': '2',
'Status de bateria': '0',
'Veiculo/Marca': 'SEM VEICULO',
},
'id' '4DDE77': {
'Tipo': 'Cartão',
'Serial': '4DDE77',
'Controlador/ID': '- - - -',
'Unidade': '44',
'Grupo': '0',
'Rec Destino': '1 ',
'Identificacao': 'MARIA',
'Ultimo Acionamento': '0',
'Status de bateria': '- - - -',
'Veiculo/Marca': 'SEM VEICULO',
},
'id' '40BF16F': {
'Tipo': 'Controle',
'Serial': '40BF16F',
'Controlador/ID': '333A',
'Unidade': '0',
'Grupo': '0',
'Rec Destino': '1 ',
'Identificacao': '00055',
'Ultimo Acionamento': '3',
'Status de bateria': '0',
'Veiculo/Marca': 'SEM VEICULO',
},
'id' '174CBA8': {
'Tipo': 'Controle',
'Serial': '174CBA8',
'Controlador/ID': '0262',
'Unidade': '0',
'Grupo': '0',
'Rec Destino': '1 ',
'Identificacao': '00056 CRISTIANO TE',
'Ultimo Acionamento': '1',
'Status de bateria': '0',
'Veiculo/Marca': 'SEM VEICULO',
},
'id' '531F44': {
'Tipo': 'Cartão',
'Serial': '531F44',
'Controlador/ID': '- - - -',
'Unidade': '24',
'Grupo': '0',
'Rec Destino': '1 ',
'Identificacao': '1',
'Ultimo Acionamento': '0',
'Status de bateria': '- - - -',
'Veiculo/Marca': 'SEM VEICULO',
},
'id' '9491989': {
'Tipo': 'Controle',
'Serial': '9491989',
'Controlador/ID': '2426',
'Unidade': '16',
'Grupo': '0',
'Rec Destino': '1 2 3 4 5 6 ',
'Identificacao': 'BIKE ELETRICA 1KW',
'Ultimo Acionamento': '0',
'Status de bateria': '0',
'Veiculo/Marca': 'SEM VEICULO',
}};